# Generated by Django 5.2.8 on 2025-12-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackTactics',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('event_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('raw_indicator', models.CharField(max_length=255)),
                ('indicator_type', models.CharField(max_length=50)),
                ('related_technique', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackTechniques',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tactic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_models.attacktactics')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_models.attacktechniques')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_models.threatevent')),
            ],
        ),
        migrations.CreateModel(
            name='EventIndicatorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_models.indicators')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_models.threatevent')),
            ],
        ),
    ]
