# Generated by Django 5.2.8 on 2025-12-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttackTactics',
            new_name='AttackTactic',
        ),
        migrations.RenameModel(
            old_name='AttackTechniques',
            new_name='AttackTechnique',
        ),
        migrations.RenameModel(
            old_name='Indicators',
            new_name='Indicator',
        ),
    ]
